# Generated by Django 5.2.4 on 2025-08-28 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubigeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('departamento', 'Departamento'), ('provincia', 'Provincia'), ('distrito', 'Distrito')], max_length=20)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ubigeo.ubigeo')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubigeos', to='tenant.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'codigo')},
            },
        ),
    ]
